---
- hosts: docker-swarm-nodes
  vars:
    swarm_clients_to_inspect: "{{ groups['docker-swarm-nodes'] }}"

  tasks:
  - name: Gathering the IP addresses of the current swarm clients and store them in temp dir
    local_action: template:
      src: templates/swarm-nodes-ip-addrs.j2
      dest: ./temp/swarm-nodes-ip-addrs.txt
