---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  #tags: [configuration,dns]

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo

- name: Let wheel group's user sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel       ALL=(ALL)       NOPASSWD: ALL'

- name: Add swarm user to the nodes
  user:
    name: "{{ swarm_user }}"
    comment: "Docker Swarm Admin"
    shell: /bin/bash
    createhome: yes
    groups: wheel

- name: copy ssh public key from swarm mangger to tmp directory
  hosts: swarm-manager
    fetch:
      src: /root/.ssh/id_rsa.pub
      dest: ./temp

# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ swarm_user }}"
#     state: present
#     key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
#
# - name: Add .ssh directory to swarm user's home directory
#   file:
#     path: /home/"{{ swarm_user }}"/.ssh/authorized_keys
#     mode: 0644
