---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  when: dns_setup
  tags: [base_config,dns]


- name: Disabling SELinux
  selinux:
    state: disabled
  tags: [base_config,selinux]

- name: yum update
  yum:
    name: '*'
    state: latest
  tags: [base_config,packages]

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - vim
  tags: [base_config,packages]

- name: Let wheel group's user sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel       ALL=(ALL)       NOPASSWD: ALL'
  tags: [base_config,ssh]

- name: Add swarm user to the nodes
  user:
    name: "{{ swarm_user }}"
    comment: "Docker Swarm Admin"
    shell: /bin/bash
    createhome: yes
    groups: wheel
  tags: [base_config,ssh]

- name: Set authorized key took from file
  authorized_key:
    user: "{{ swarm_user }}"
    state: present
    key: "{{ lookup('file', 'temp/{{swarm_manager_name}}/root/.ssh/id_rsa.pub') }}"
  tags: [base_config,ssh]

- name: change the .ssh directory permission
  file:
    path: /home/"{{ swarm_user }}"/.ssh
    state: directory
    owner: "{{ swarm_user }}"
    mode: 0700
  tags: [base_config,ssh]

- name: change the .ssh/authorized_key file permission
  file:
    path: /home/{{swarm_user}}/.ssh/authorized_keys
    state: file
    owner: "{{ swarm_user }}"
    mode: 0644
  tags: [base_config,ssh]
