---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  #tags: [configuration,dns]

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Add necessary packages
  yum:
    name: sudo
    state: present
