---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  when: dns_setup
  tags: [base_config,dns]

- name: Disabling SELinux
  selinux:
    state: disabled
  tags: [base_config,selinux]

- name: Run yum update
  yum:
    name: '*'
    state: latest
  tags: [base_config,packages]

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - epel-release
    - sudo
    - yum-utils
    - vim
    - bash-completion
    - pdsh
  tags: [base_config,packages]

- name: Create ssh key pairs for user root on swarm manager
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags: [base_config,ssh]

- name: Fetch ssh public key from swarm mangger to the local tmp directory
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: ./temp
    fail_on_missing: yes
  tags: [base_config,ssh]

- name: Add Dcoker CE repository
  command: /usr/bin/yum-config-manager --add-repo "{{ Docker_repo_address }}"
  tags: [base_config,docker]

- name: Install Docker CE
  yum:
    name: "{{ Docker_CE_version }}"
    state: present
    update_cache: yes
  when: Docker_version
  tags: [base_config,docker]

- name: Start and enable Docker CE service
  service:
    name: docker
    state: started
    enabled: yes
  tags: [base_config,docker]

- name: Re-Install glibc-common package to add necessary locales
  command: yum reinstall -y glibc-common
  when: Reinstall_glibc_common
  tags: [base_config,locale]

- name: Set locale for en_US.utf8
  command: localectl set-locale LANG="{{ locale }}"
  when: Set_locale
  tags: [base_config,locale]

- name: Install Docker machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v{{Docker_machine_version}}/docker-machine-{{Docker_machine_OS}}-{{Docker_machine_arch}}
    dest: /usr/local/bin/docker-machine
    mode: 755
    force: yes
  tags:
    - curl
  tags: [base_config,docker-machine]
