---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  #tags: [configuration,dns]

- name: Disabling SELinux
  selinux:
    state: disabled

- name: Run yum update
  yum:
    name: '*'
    state: latest

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - yum-utils

- name: Create ssh key pairs for user root on swarm manager
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Fetch ssh public key from swarm mangger to the local tmp directory
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: ./temp
    fail_on_missing: yes

- name: Add Dcoker CE repository
  command: /usr/bin/yum-config-manager --add-repo "{{ docker_repo_address }}"

- name: Install Docker CE
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  when: not docker_version

- name: Install Docker CE
  yum:
    name: "{{ Docker_CE_Version }}"
    state: present
    update_cache: yes
  when: docker_version

- name: Start and enable Docker CE service
  service:
    name: docker
    state: started
    enabled: yes

- name: Re-Install glibc-common package to add necessary locales
  command: yum reinstall -y glibc-common
