---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  #tags: [configuration,dns]

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo

- user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
