---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  #tags: [configuration,dns]

- name: Disabling SELinux
  selinux:
    state: disabled

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - yum-utils

- name: create ssh key pairs for user root on swarm manager
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: fetch ssh public key from swarm mangger to the local tmp directory
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: ./temp
    fail_on_missing: yes

- name: Add Dcoker CE repository
  yum_repository:
    name: docker-ceee
    description: Docker CE repository
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
