---
dns_setup: false
dns_nameservers: ['8.8.8.8', '8.8.4.4']
dns_remove_resolvconf: true
dns_domain: "hpcc.ttu.edu"
dns_searchs:
   - "{{dns_domain}}"

#set the name of the following parameter form hosts file, more useful if we plan to have more than one manager
#swarm_manager_name: "swarm-manager"
