---
- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  when: dns_setup
  tags: [base_config,dns]


- name: Disabling SELinux
  selinux:
    state: disabled
  tags: [base_config,selinux]

- name: yum update
  yum:
    name: '*'
    state: latest
  tags: [base_config,packages]

- name: Add epel repository
  yum: name={{item}} state=present
  with_items:
    - epel-release
  tags: [base_config,packages]

- name: Add necessary packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - yum-utils
    - vim
    - bash-completion
  tags: [base_config,packages]

- name: Let wheel group's user sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel       ALL=(ALL)       NOPASSWD: ALL'
  when: Install_by_docker_machine
  tags: [base_config,ssh]

- name: Add swarm user to the workers
  user:
    name: swarmadmin
    comment: "Docker Swarm Admin"
    shell: /bin/bash
    createhome: yes
    groups: wheel
  when: Install_by_docker_machine
  tags: [base_config,ssh]

- name: Set the authorized key from a file (for swarm user)
  authorized_key:
    user: swarmadmin
    state: present
    key: "{{ lookup('file', 'temp/swarm-manager/root/.ssh/id_rsa_2048_swarmadmin.pub') }}"
  when: Install_by_docker_machine
  tags: [base_config,ssh]

- name: Set the authorized key from a file (for root user)
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'temp/swarm-manager/root/.ssh/id_rsa_2048_root.pub') }}"
  tags: [base_config,ssh]

- name: change the .ssh directory permission
  file:
    path: /home/swarmadmin/.ssh
    state: directory
    owner: swarmadmin
    mode: 0700
  when: Install_by_docker_machine
  tags: [base_config,ssh]

- name: change the .ssh/authorized_key file permission
  file:
    path: /home/swarmadmin/.ssh/authorized_keys
    state: file
    owner: swarmadmin
    mode: 0644
  when: Install_by_docker_machine
  tags: [base_config,ssh]

- name: Add Dcoker CE repository
  command: /usr/bin/yum-config-manager --add-repo "{{ Docker_repo_address }}"
  when: not Install_by_docker_machine
  tags: [base_config,docker]

- name: Install Docker CE (specific version)
  yum:
    name: "docker-ce-{{ Docker_CE_version }}"
    state: present
    update_cache: yes
  when: not Install_by_docker_machine and Docker_version
  tags: [base_config,docker]

- name: Install Docker CE (latest version)
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  when: not Install_by_docker_machine and not Docker_version
  tags: [base_config,docker]

- name: Start and enable Docker CE service
  service:
    name: docker
    state: started
    enabled: yes
  when: not Install_by_docker_machine
  tags: [base_config,docker]
